(function () {
  function options(correct, wrongs, answer) {
    const result = wrongs.slice(0, 3);
    result.splice(answer, 0, correct);
    return result;
  }

  function buildLevel(facts, lang) {
    return facts.flatMap((fact, index) => {
      const answer = index % 4;
      const tfOptions = lang === "sw" ? ["Kweli", "Si kweli", "Haijatajwa", "Inategemea"] : ["True", "False", "Not stated", "It depends"];
      const directPrefix = lang === "sw" ? "Chagua jibu sahihi: " : "Choose the correct answer: ";
      const truePrefix = lang === "sw" ? "Kweli au si kweli: " : "True or false: ";
      return [
        {
          question: directPrefix + fact.question,
          options: options(fact.correct, fact.wrongs, answer),
          answer,
          explain: fact.explain,
        },
        {
          question: truePrefix + fact.statement,
          options: tfOptions,
          answer: 0,
          explain: fact.explain,
        },
        {
          question: fact.application,
          options: options(fact.correct, fact.wrongs, (answer + 2) % 4),
          answer: (answer + 2) % 4,
          explain: fact.explain,
        },
      ];
    });
  }

  const sw = {
    beginner: [
      { question: "Muungano uliundwa rasmi mwaka gani?", statement: "Muungano wa Tanganyika na Zanzibar uliundwa rasmi tarehe 26 Aprili 1964.", application: "Mwanafunzi akiuliza siku rasmi ya Muungano, jibu lipi ni sahihi?", correct: "26 Aprili 1964", wrongs: ["12 Januari 1964", "9 Desemba 1961", "26 Aprili 1977"], explain: "Siku rasmi ya kuundwa kwa Jamhuri ya Muungano ni 26 Aprili 1964." },
      { question: "Hati za Muungano zilisainiwa tarehe gani?", statement: "Hati za Muungano zilisainiwa kabla ya siku rasmi ya Muungano.", application: "Unapotengeneza timeline, tukio la kusainiwa Hati za Muungano linawekwa tarehe gani?", correct: "22 Aprili 1964", wrongs: ["26 Aprili 1964", "12 Januari 1964", "7 Aprili 1972"], explain: "Hati za Muungano zilisainiwa tarehe 22 Aprili 1964." },
      { question: "Ni nchi zipi ziliungana kuunda Jamhuri ya Muungano?", statement: "Muungano uliunganisha Tanganyika na Zanzibar.", application: "Kwenye ramani ya historia, pande mbili za Muungano ni zipi?", correct: "Tanganyika na Zanzibar", wrongs: ["Kenya na Tanganyika", "Uganda na Zanzibar", "Pemba na Unguja"], explain: "Muungano uliundwa na Tanganyika na Zanzibar." },
      { question: "Nani alikuwa Rais wa Tanganyika wakati wa Muungano?", statement: "Julius Kambarage Nyerere alikuwa mmoja wa waasisi wa Muungano.", application: "Ukimtaja mwanzilishi kutoka Tanganyika, jina gani linafaa?", correct: "Julius Kambarage Nyerere", wrongs: ["Abeid Amani Karume", "Rashid Kawawa", "Ali Hassan Mwinyi"], explain: "Nyerere alikuwa Rais wa Tanganyika na mmoja wa waasisi wa Muungano." },
      { question: "Nani alikuwa Rais wa Zanzibar wakati wa Muungano?", statement: "Abeid Amani Karume alikuwa mmoja wa waasisi wa Muungano.", application: "Ukimtaja mwanzilishi kutoka Zanzibar, jina gani linafaa?", correct: "Abeid Amani Karume", wrongs: ["Julius Nyerere", "Rashid Kawawa", "Jakaya Kikwete"], explain: "Karume alikuwa Rais wa Zanzibar na Mwenyekiti wa Baraza la Mapinduzi." },
      { question: "Mapinduzi ya Zanzibar yalitokea tarehe gani?", statement: "Mapinduzi ya Zanzibar yalitangulia Muungano wa Aprili 1964.", application: "Tukio gani la Januari 1964 lilihusiana na historia ya Muungano?", correct: "12 Januari 1964", wrongs: ["22 Aprili 1964", "26 Aprili 1964", "9 Desemba 1961"], explain: "Mapinduzi ya Zanzibar yalitokea tarehe 12 Januari 1964." },
      { question: "Katiba ya Jamhuri ya Muungano inayotajwa sana ni ya mwaka gani?", statement: "Katiba ya Jamhuri ya Muungano ya mwaka 1977 ni msingi muhimu wa kikatiba.", application: "Ukitafuta msingi wa sasa wa Katiba ya Muungano, mwaka gani unaonekana?", correct: "1977", wrongs: ["1961", "1964", "1984"], explain: "Katiba ya Jamhuri ya Muungano wa Tanzania ni ya mwaka 1977." },
      { question: "Katiba ya Zanzibar inayotumika ndani ya mfumo huu ni ya mwaka gani?", statement: "Katiba ya Zanzibar ya 1984 inaeleza taasisi za Serikali ya Mapinduzi ya Zanzibar.", application: "Mwanafunzi akiuliza Katiba ya Zanzibar inayorejelewa mara nyingi, jibu ni lipi?", correct: "1984", wrongs: ["1964", "1977", "1992"], explain: "Katiba ya Zanzibar inayorejelewa sana ni ya mwaka 1984." },
      { question: "Moja ya Mambo ya Muungano ni lipi?", statement: "Uraia ni miongoni mwa Mambo ya Muungano.", application: "Kwenye orodha ya Mambo ya Muungano, chagua mfano sahihi.", correct: "Uraia", wrongs: ["Soko la kijiji", "Michezo ya shule", "Ratiba ya darasa"], explain: "Uraia ni moja ya mambo yanayoshughulikiwa katika ngazi ya Muungano." },
      { question: "Muungano una umuhimu gani kwa vijana?", statement: "Muungano unasaidia umoja, utambulisho wa pamoja na kujifunza historia.", application: "Kijana akitaka kueleza faida ya Muungano kwa jamii, aseme nini?", correct: "Unaimarisha umoja na utambulisho wa pamoja", wrongs: ["Unafuta historia", "Unazuia elimu", "Unatenganisha wananchi"], explain: "Muungano unaimarisha umoja wa kitaifa na uelewa wa historia." },
      { question: "Changamoto za Muungano zinapaswa kujadiliwa kwa njia gani?", statement: "Changamoto za Muungano zinahitaji heshima, vyanzo sahihi na mazungumzo ya kujenga.", application: "Mwanafunzi akisikia hoja kuhusu Muungano, hatua nzuri ya kwanza ni ipi?", correct: "Kutafuta chanzo sahihi", wrongs: ["Kuamini uvumi", "Kukataa maswali yote", "Kusambaza taarifa bila uhakika"], explain: "Changamoto zinapaswa kujadiliwa kwa maarifa, vyanzo na lugha ya heshima." },
      { question: "Mfano rahisi wa changamoto ya Muungano ni upi?", statement: "Uelewa mdogo wa wananchi kuhusu Mambo ya Muungano unaweza kuwa changamoto.", application: "Kijana akichanganya majukumu ya Muungano na yasiyo ya Muungano, tatizo ni nini?", correct: "Uelewa mdogo wa masuala ya Muungano", wrongs: ["Kujua tarehe sahihi", "Kusoma Katiba", "Kutumia vyanzo rasmi"], explain: "Elimu kwa umma husaidia kupunguza mkanganyiko kuhusu majukumu na Mambo ya Muungano." },
    ],
    intermediate: [
      { question: "Kwa nini mahusiano ya kihistoria yalisaidia Muungano?", statement: "Ujirani, biashara, Kiswahili na mahusiano ya kijamii yaliunda msingi wa Muungano.", application: "Ukiandika sababu za Muungano, hoja ipi inaonyesha msingi wa kijamii?", correct: "Mahusiano ya karibu ya kihistoria", wrongs: ["Ukosefu wa mawasiliano", "Umbali wa kijiografia", "Kutokuwepo kwa biashara"], explain: "Vyanzo vinaeleza historia, ujirani, biashara, lugha na uhusiano wa kisiasa kama sababu muhimu." },
      { question: "Ni vyama gani vilihusishwa na ushirikiano wa kisiasa kabla ya Muungano?", statement: "TANU na ASP vilikuwa na ushirikiano uliotajwa katika sababu za Muungano.", application: "Mjadala ukihusu vyama vilivyokaribiana kisiasa, chagua jibu sahihi.", correct: "TANU na ASP", wrongs: ["CCM na CUF", "ANC na ZPPP", "ZNP na UTP"], explain: "Ushirikiano wa TANU na ASP ni miongoni mwa sababu zilizotajwa." },
      { question: "Mabadiliko ya mfumo wa vyama vingi yalitokea mwaka gani?", statement: "Mwaka 1992 Tanzania ilipitisha mfumo wa demokrasia ya vyama vingi.", application: "Ukiweka mageuzi ya vyama vingi kwenye timeline, mwaka gani unaandika?", correct: "1992", wrongs: ["1964", "1977", "1984"], explain: "Mfumo wa vyama vingi ulipitishwa mwaka 1992." },
      { question: "Baada ya mageuzi ya 1992, nafasi ya Rais wa Zanzibar kwenye Muungano ilibadilika vipi?", statement: "Baada ya 1992, Rais wa Zanzibar hakuwa tena Makamu wa Rais wa Muungano moja kwa moja.", application: "Swali la katiba likiuliza mabadiliko ya Makamu wa Rais, jibu lipi linafaa?", correct: "Mfumo wa mgombea mwenza uliimarishwa", wrongs: ["Muungano ulivunjwa", "Bunge liliondolewa", "Zanzibar ilifuta Katiba"], explain: "Mageuzi ya vyama vingi yalihusisha mfumo wa mgombea mwenza wa Rais na Makamu wa Rais." },
      { question: "Mambo ya Muungano yako mangapi kwenye orodha inayotumika sasa?", statement: "Orodha inayofundishwa mara nyingi hutaja Mambo 22 ya Muungano.", application: "Mwalimu akiuliza idadi ya Mambo ya Muungano, jibu ni lipi?", correct: "22", wrongs: ["7", "11", "30"], explain: "Orodha ya sasa inatajwa kama Mambo 22 ya Muungano." },
      { question: "Ni taasisi gani ya haki ni jambo la Muungano?", statement: "Mahakama ya Rufani ya Jamhuri ya Muungano ni miongoni mwa Mambo ya Muungano.", application: "Kwenye somo la taasisi, chagua taasisi ya Muungano.", correct: "Mahakama ya Rufani ya Jamhuri ya Muungano", wrongs: ["Mahakama ya kijiji", "Kamati ya shule", "Soko la wilaya"], explain: "Mahakama ya Rufani ni moja ya mambo yaliyoorodheshwa katika Mambo ya Muungano." },
      { question: "Kwa nini chanzo rasmi ni muhimu kwenye elimu ya Muungano?", statement: "Chanzo rasmi hupunguza upotoshaji na husaidia kuthibitisha majibu.", application: "Chatbot ikitoa jibu kuhusu tarehe, kipengele gani kinajenga uaminifu?", correct: "Rejea au source citation", wrongs: ["Rangi ya kitufe", "Ukubwa wa nembo", "Kuficha nyaraka"], explain: "Rejea zinasaidia mtumiaji kukagua ushahidi wa jibu." },
      { question: "Mambo ya nje yanahusiana vipi na Muungano?", statement: "Mambo ya nchi za nje ni mojawapo ya Mambo ya Muungano.", application: "Ukiulizwa mfano wa jukumu la kimataifa la Muungano, chagua lipi?", correct: "Mambo ya nchi za nje", wrongs: ["Ratiba ya mitihani ya shule", "Bei ya sokoni", "Mashindano ya mtaa"], explain: "Mambo ya nje ni jambo la Muungano." },
      { question: "Elimu ya juu ina nafasi gani katika Mambo ya Muungano?", statement: "Elimu ya juu ni miongoni mwa Mambo 22 ya Muungano.", application: "Kwenye orodha ya Mambo ya Muungano, sekta gani ya elimu imo?", correct: "Elimu ya juu", wrongs: ["Elimu ya awali pekee", "Ratiba ya darasa", "Sare za shule"], explain: "Elimu ya juu imeorodheshwa kama jambo la Muungano." },
      { question: "Hoja za Muungano zinaposhughulikiwa, lengo kuu ni lipi?", statement: "Baadhi ya hoja za Muungano hupatiwa ufumbuzi na nyingine huendelea kutafutiwa ufumbuzi.", application: "Mjadala ukitaja changamoto za Muungano, mtazamo sahihi ni upi?", correct: "Kuzijadili na kuzitafutia ufumbuzi", wrongs: ["Kuzificha kabisa", "Kufuta Katiba", "Kuzuia elimu kwa umma"], explain: "Vyanzo rasmi hutaja hoja zilizopatiwa ufumbuzi na zinazoendelea kushughulikiwa." },
      { question: "Kwa nini baadhi ya wananchi huchanganya Mambo ya Muungano?", statement: "Ukosefu wa elimu ya kutosha unaweza kufanya watu wachanganye majukumu ya serikali.", application: "Ukiona swali linauliza kama kila huduma ni ya Muungano, unapaswa kufanya nini?", correct: "Kutofautisha jambo la Muungano na lisilo la Muungano", wrongs: ["Kusema kila kitu ni cha Muungano", "Kuepuka Katiba", "Kukisia bila kusoma"], explain: "Uelewa wa mipaka ya majukumu ni sehemu muhimu ya elimu ya Muungano." },
      { question: "Njia bora ya kushughulikia taarifa potofu kuhusu Muungano ni ipi?", statement: "Taarifa potofu hupunguzwa kwa kutumia nyaraka, Katiba na elimu kwa umma.", application: "Chatbot ikijibu hoja tata, nini kiwepo ili kupunguza upotoshaji?", correct: "Vyanzo vinavyoonekana", wrongs: ["Majibu bila ushahidi", "Kauli za hasira", "Kuficha chanzo"], explain: "Citations na nyaraka hufanya majibu yaweze kukaguliwa na kuaminiwa." },
      { question: "Kwa nini mtazamo wa pande zote mbili ni muhimu kwenye changamoto za Muungano?", statement: "Hoja za Muungano huhitaji kuelewa Tanzania Bara na Zanzibar.", application: "Mjadala wa heshima kuhusu Muungano unatakiwa kusikiliza nani?", correct: "Pande zote mbili za Muungano", wrongs: ["Upande mmoja tu", "Uvumi wa mitandaoni", "Watu wasiojua historia"], explain: "Uelewa wa pande zote husaidia kujenga majibu ya haki na yenye mshikamano." },
    ],
    expert: [
      { question: "Hati za Muungano zina uhusiano gani na Katiba za baadaye?", statement: "Hati za Muungano za 1964 ni msingi wa Katiba ya Jamhuri ya Muungano na Katiba ya Zanzibar.", application: "Ukitathmini asili ya mfumo wa kikatiba, rejea ipi ni ya msingi?", correct: "Hati za Muungano za 1964", wrongs: ["Hotuba ya kampeni", "Ratiba ya uchaguzi", "Taarifa ya michezo"], explain: "Vyanzo rasmi hueleza Hati za Muungano kama msingi wa Katiba za baadaye." },
      { question: "Kwa nini Aprili 27, 1964 ni muhimu katika historia ya Muungano?", statement: "Tarehe 27 Aprili 1964 waasisi walibadilishana Hati za Muungano na baadhi ya wajumbe waliapishwa.", application: "Timeline ya kina ikiuliza tukio la siku baada ya kuundwa rasmi, chagua lipi.", correct: "Kubadilishana Hati za Muungano", wrongs: ["Uhuru wa Tanganyika", "Mapinduzi ya Zanzibar", "Katiba ya 1977 kuanza"], explain: "Tarehe 27 Aprili 1964 ilihusisha kubadilishana Hati na kuapishwa kwa wajumbe kutoka Zanzibar." },
      { question: "Kwa nini mfumo wa serikali mbili ni hoja muhimu ya Muungano?", statement: "Muundo wa Muungano ulihusisha Serikali ya Jamhuri ya Muungano na Serikali ya Mapinduzi ya Zanzibar.", application: "Mwanafunzi akiuliza muundo wa sasa wa Muungano, jibu lipi linafaa?", correct: "Mfumo wa serikali mbili", wrongs: ["Serikali moja ya mkoa", "Serikali tano", "Hakuna serikali"], explain: "Muungano wa Tanzania unafahamika kwa muundo wa serikali mbili." },
      { question: "Ni suala gani linaonyesha changamoto za fedha katika hoja za Muungano?", statement: "Mapendekezo ya Tume ya Pamoja ya Fedha yametajwa miongoni mwa hoja zinazoendelea kushughulikiwa.", application: "Ukiainisha hoja ya kifedha, chagua mfano sahihi.", correct: "Mapendekezo ya Tume ya Pamoja ya Fedha", wrongs: ["Sare za wanafunzi", "Lugha ya darasani", "Picha za kumbukumbu"], explain: "Tume ya Pamoja ya Fedha ni moja ya hoja zinazotajwa katika masuala ya Muungano." },
      { question: "Kwa nini RAG chatbot inahitaji retrieval kabla ya kujibu?", statement: "Retrieval hutafuta vipande vya nyaraka vinavyohusiana na swali kabla ya jibu kutengenezwa.", application: "Mtumiaji akiuliza swali gumu la Katiba, mfumo unapaswa kufanya nini kwanza?", correct: "Kutafuta ushahidi kwenye nyaraka", wrongs: ["Kubuni bila chanzo", "Kubadili rangi", "Kufuta swali"], explain: "RAG hutegemea retrieval ili majibu yajengwe kwenye vyanzo." },
      { question: "Ni jambo gani linaonyesha usahihi wa juu kwenye elimu ya kidigitali?", statement: "Majibu yenye vyanzo, tarehe kamili na mipaka ya uhakika hupunguza makosa.", application: "Ukiamua kuboresha MuunganoHub, kipaumbele gani ni cha kitaaluma zaidi?", correct: "Majibu yenye citations na tarehe", wrongs: ["Majibu marefu bila vyanzo", "Nembo kubwa tu", "Kufunga maswali"], explain: "Elimu ya historia inahitaji ushahidi, tarehe na vyanzo vinavyoonekana." },
      { question: "Mambo 22 ya Muungano yanasaidia nini katika somo la uraia?", statement: "Orodha ya Mambo ya Muungano husaidia kuelewa mipaka ya majukumu ya Muungano.", application: "Mwanafunzi akichanganya majukumu ya Serikali, orodha ipi imsaidie?", correct: "Mambo 22 ya Muungano", wrongs: ["Majina ya mitaa", "Ratiba ya vipindi", "Matokeo ya michezo"], explain: "Mambo 22 yanaonyesha maeneo yanayoshughulikiwa kama masuala ya Muungano." },
      { question: "Kwa nini historia ya pamoja kabla ya 1964 ni muhimu?", statement: "Historia ya biashara, lugha, ujirani na harakati za ukombozi ilisaidia kuhalalisha Muungano.", application: "Ukiandika insha ya sababu za Muungano, hoja ya kina ni ipi?", correct: "Misingi ya kijamii na kihistoria kabla ya 1964", wrongs: ["Matukio ya baada ya 2020 pekee", "Michezo ya shule", "Utalii pekee"], explain: "Muungano haukutokea ghafla; ulikuwa na misingi ya muda mrefu." },
      { question: "Kwa nini hoja za Muungano haziwezi kufundishwa kama orodha tu?", statement: "Hoja za Muungano zinahitaji kueleza historia, taasisi, ufumbuzi na hoja zinazoendelea.", application: "Somu la expert linapaswa kuongeza nini zaidi ya kukariri?", correct: "Uchambuzi wa sababu na ufumbuzi", wrongs: ["Majina bila maana", "Majibu ya neno moja", "Kuepuka vyanzo"], explain: "Uelewa wa juu unahitaji kuchambua chanzo cha hoja na namna zinavyoshughulikiwa." },
      { question: "Kwa nini miaka 60 ya Muungano ilikuwa hatua ya elimu kwa umma?", statement: "Maadhimisho ya miaka 60 yalitoa nafasi ya kutafakari historia, mafanikio na mijadala ya Muungano.", application: "Ukiunda somo la sasa kuhusu Muungano, tukio gani la 2024 linafaa?", correct: "Maadhimisho ya miaka 60 ya Muungano", wrongs: ["Uhuru wa Tanganyika 1961", "Katiba ya Zanzibar 1984", "Mageuzi ya 1992 pekee"], explain: "Mwaka 2024 ulihusishwa na kumbukumbu ya miaka 60 ya Muungano." },
      { question: "Kwa nini hoja za kifedha ni nyeti katika Muungano?", statement: "Hoja za fedha huhitaji uwazi, taasisi na usawa katika utekelezaji wa majukumu.", application: "Ukiandaa mjadala wa expert kuhusu fedha za Muungano, kipaumbele ni kipi?", correct: "Uwazi wa taasisi na uchambuzi wa ushahidi", wrongs: ["Kauli bila takwimu", "Kulaumu bila chanzo", "Kufuta historia"], explain: "Hoja za kifedha zinahitaji ushahidi na mchakato wa kitaasisi ili kuepuka upotoshaji." },
      { question: "Kwa nini changamoto za Muungano zinahitaji civic education endelevu?", statement: "Elimu endelevu husaidia kizazi kipya kuelewa hoja, vyanzo na njia za utatuzi.", application: "Mradi wa kidigitali ukitaka kusaidia mjadala wa Muungano, ufanye nini?", correct: "Kutoa elimu yenye vyanzo na mifano", wrongs: ["Kutoa majibu yasiyo na rejea", "Kuepuka maswali magumu", "Kutumia mada moja tu"], explain: "Changamoto za Muungano hubadilika na kujadiliwa; elimu endelevu husaidia wananchi kufuatilia kwa usahihi." },
      { question: "Kipi kinaonyesha uchambuzi wa juu wa changamoto ya Muungano?", statement: "Uchambuzi mzuri hutaja chanzo cha hoja, taasisi husika, hatua zilizochukuliwa na hali ya sasa.", application: "Jibu la expert kuhusu changamoto linapaswa kuwa na nini?", correct: "Chanzo, taasisi, hatua na hali ya sasa", wrongs: ["Hisia pekee", "Jina la kiongozi tu", "Tarehe bila maelezo"], explain: "Uchambuzi wa kitaalamu hauishii kutaja changamoto; unaonyesha muktadha na njia za utatuzi." },
    ],
  };

  const en = {
    beginner: [
      { question: "In which year was the Union officially formed?", statement: "The Union of Tanganyika and Zanzibar was officially formed on 26 April 1964.", application: "If a student asks for Union Day, which answer is correct?", correct: "26 April 1964", wrongs: ["12 January 1964", "9 December 1961", "26 April 1977"], explain: "The United Republic was officially formed on 26 April 1964." },
      { question: "When were the Articles of Union signed?", statement: "The Articles of Union were signed before the official Union Day.", application: "On a timeline, which date marks the signing of the Articles of Union?", correct: "22 April 1964", wrongs: ["26 April 1964", "12 January 1964", "7 April 1972"], explain: "The Articles of Union were signed on 22 April 1964." },
      { question: "Which two countries formed the Union?", statement: "The Union brought together Tanganyika and Zanzibar.", application: "On a historical map, which two sides should be shown?", correct: "Tanganyika and Zanzibar", wrongs: ["Kenya and Tanganyika", "Uganda and Zanzibar", "Pemba and Unguja"], explain: "The Union was formed by Tanganyika and Zanzibar." },
      { question: "Who was President of Tanganyika at the time of the Union?", statement: "Julius Kambarage Nyerere was one of the founders of the Union.", application: "Which founder should be named from Tanganyika?", correct: "Julius Kambarage Nyerere", wrongs: ["Abeid Amani Karume", "Rashid Kawawa", "Ali Hassan Mwinyi"], explain: "Nyerere was President of Tanganyika and a founder of the Union." },
      { question: "Who was President of Zanzibar at the time of the Union?", statement: "Abeid Amani Karume was one of the founders of the Union.", application: "Which founder should be named from Zanzibar?", correct: "Abeid Amani Karume", wrongs: ["Julius Nyerere", "Rashid Kawawa", "Jakaya Kikwete"], explain: "Karume was President of Zanzibar and Chairman of the Revolutionary Council." },
      { question: "When did the Zanzibar Revolution take place?", statement: "The Zanzibar Revolution came before the Union of April 1964.", application: "Which January 1964 event is linked to Union history?", correct: "12 January 1964", wrongs: ["22 April 1964", "26 April 1964", "9 December 1961"], explain: "The Zanzibar Revolution took place on 12 January 1964." },
      { question: "Which year is linked to the Constitution of the United Republic?", statement: "The 1977 Constitution is an important constitutional foundation.", application: "If you search for the current Union constitutional foundation, which year appears?", correct: "1977", wrongs: ["1961", "1964", "1984"], explain: "The Constitution of the United Republic of Tanzania is associated with 1977." },
      { question: "Which year is linked to the Constitution of Zanzibar?", statement: "The 1984 Constitution of Zanzibar describes Zanzibar's revolutionary government institutions.", application: "If a student asks for the commonly referenced Zanzibar Constitution, what is the answer?", correct: "1984", wrongs: ["1964", "1977", "1992"], explain: "The commonly referenced Constitution of Zanzibar is from 1984." },
      { question: "Which is one Union matter?", statement: "Citizenship is one of the Union matters.", application: "From the Union matters list, choose a correct example.", correct: "Citizenship", wrongs: ["Village market", "School games", "Class timetable"], explain: "Citizenship is handled at Union level." },
      { question: "Why does the Union matter to young people?", statement: "The Union supports unity, shared identity, and learning history.", application: "How should a young person describe a social benefit of the Union?", correct: "It strengthens unity and shared identity", wrongs: ["It deletes history", "It blocks education", "It separates citizens"], explain: "The Union strengthens national unity and historical understanding." },
      { question: "How should Union challenges be discussed?", statement: "Union challenges need respect, reliable sources, and constructive dialogue.", application: "If a student hears a Union issue being discussed, what should they do first?", correct: "Look for a reliable source", wrongs: ["Trust rumours", "Reject every question", "Share unverified claims"], explain: "Union challenges should be discussed with evidence, respect, and source-based learning." },
      { question: "Which simple example can become a Union challenge?", statement: "Limited public understanding of Union matters can become a challenge.", application: "If a young person confuses Union and non-Union responsibilities, what is the problem?", correct: "Limited understanding of Union matters", wrongs: ["Knowing the correct date", "Reading the Constitution", "Using official sources"], explain: "Public education helps reduce confusion about Union responsibilities." },
    ],
    intermediate: [
      { question: "Why did historical relations support the Union?", statement: "Neighbourhood, trade, Swahili, and social relations helped form a foundation for the Union.", application: "In a lesson on reasons for the Union, which answer shows the social foundation?", correct: "Close historical relations", wrongs: ["Lack of communication", "Geographical distance", "Absence of trade"], explain: "Official sources mention history, closeness, trade, language, and political links as key reasons." },
      { question: "Which parties were linked by political cooperation before the Union?", statement: "TANU and ASP are mentioned as parties with cooperation before the Union.", application: "In a political-history discussion, which pair is correct?", correct: "TANU and ASP", wrongs: ["CCM and CUF", "ANC and ZPPP", "ZNP and UTP"], explain: "Cooperation between TANU and ASP is one of the stated reasons." },
      { question: "In which year did multiparty democracy reforms occur?", statement: "In 1992 Tanzania adopted a multiparty democratic system.", application: "Where should multiparty reform be placed on the timeline?", correct: "1992", wrongs: ["1964", "1977", "1984"], explain: "The multiparty system was adopted in 1992." },
      { question: "How did the 1992 reforms affect the Union vice-presidency arrangement?", statement: "After 1992, the President of Zanzibar was no longer automatically Union Vice President.", application: "If a constitutional question asks about the Vice President change, which answer fits?", correct: "The running-mate system was strengthened", wrongs: ["The Union was dissolved", "Parliament was removed", "Zanzibar abolished its Constitution"], explain: "Multiparty reforms introduced the presidential running-mate arrangement." },
      { question: "How many Union matters are commonly listed today?", statement: "The list commonly taught today refers to 22 Union matters.", application: "If a teacher asks for the number of Union matters, what is the answer?", correct: "22", wrongs: ["7", "11", "30"], explain: "The current list is commonly presented as 22 Union matters." },
      { question: "Which justice institution is a Union matter?", statement: "The Court of Appeal of the United Republic is one of the Union matters.", application: "In an institutions lesson, choose the Union institution.", correct: "Court of Appeal of the United Republic", wrongs: ["Village court", "School committee", "District market"], explain: "The Court of Appeal is listed among Union matters." },
      { question: "Why is an official source important in Union education?", statement: "An official source reduces misinformation and helps verify answers.", application: "If a chatbot gives a date answer, which feature builds trust?", correct: "A reference or source citation", wrongs: ["Button color", "Logo size", "Hidden documents"], explain: "References let users check the evidence behind an answer." },
      { question: "How are foreign affairs connected to the Union?", statement: "Foreign affairs are one of the Union matters.", application: "If asked for an international role of the Union, which answer fits?", correct: "Foreign affairs", wrongs: ["School exam timetable", "Market prices", "Street competitions"], explain: "Foreign affairs are a Union matter." },
      { question: "What place does higher education have among Union matters?", statement: "Higher education is one of the 22 Union matters.", application: "Which education sector appears in the Union matters list?", correct: "Higher education", wrongs: ["Pre-primary only", "Class timetable", "School uniforms"], explain: "Higher education is listed as a Union matter." },
      { question: "What is the main purpose of addressing Union issues?", statement: "Some Union issues have been resolved and others continue to be addressed.", application: "If a discussion mentions Union challenges, what is the right approach?", correct: "Discussing them and seeking solutions", wrongs: ["Hiding them completely", "Deleting the Constitution", "Stopping public education"], explain: "Official sources list resolved issues and issues still being worked on." },
      { question: "Why do some citizens confuse Union matters?", statement: "Insufficient public education can make citizens confuse government responsibilities.", application: "If someone asks whether every public service is a Union matter, what should you do?", correct: "Separate Union matters from non-Union matters", wrongs: ["Say everything is a Union matter", "Avoid the Constitution", "Guess without reading"], explain: "Knowing the boundary of responsibilities is a key part of Union education." },
      { question: "What is the best way to respond to misinformation about the Union?", statement: "Misinformation is reduced through documents, constitutions, and public education.", application: "If a chatbot answers a sensitive Union issue, what should it include?", correct: "Visible sources", wrongs: ["Answers without evidence", "Angry statements", "Hidden references"], explain: "Sources and citations make answers checkable and trustworthy." },
      { question: "Why is listening to both sides important in Union challenges?", statement: "Union issues require understanding both Mainland Tanzania and Zanzibar.", application: "A respectful Union discussion should listen to whom?", correct: "Both sides of the Union", wrongs: ["One side only", "Online rumours", "People without historical context"], explain: "Understanding both sides supports fair and constructive civic discussion." },
    ],
    expert: [
      { question: "How do the Articles of Union relate to later constitutions?", statement: "The 1964 Articles of Union are a foundation for the Union Constitution and Zanzibar Constitution.", application: "When analysing the origin of the constitutional framework, what is the key reference?", correct: "The 1964 Articles of Union", wrongs: ["A campaign speech", "An election timetable", "A sports report"], explain: "Official sources describe the Articles of Union as a foundation for later constitutional arrangements." },
      { question: "Why is 27 April 1964 important in Union history?", statement: "On 27 April 1964 the founders exchanged the Articles of Union and some members were sworn in.", application: "On a detailed timeline, what happened the day after official Union Day?", correct: "Exchange of the Articles of Union", wrongs: ["Tanganyika independence", "Zanzibar Revolution", "The 1977 Constitution began"], explain: "27 April 1964 involved exchanging Articles and swearing in members from Zanzibar." },
      { question: "Why is the two-government structure important?", statement: "The Union structure includes the Union Government and the Revolutionary Government of Zanzibar.", application: "If a student asks about the current Union structure, which answer fits?", correct: "A two-government structure", wrongs: ["One regional government", "Five governments", "No government"], explain: "Tanzania's Union is commonly described through a two-government structure." },
      { question: "Which issue shows the financial side of Union challenges?", statement: "Recommendations of the Joint Finance Commission are mentioned among issues still being handled.", application: "When identifying a financial Union issue, choose the correct example.", correct: "Recommendations of the Joint Finance Commission", wrongs: ["Student uniforms", "Class language", "Archive photos"], explain: "The Joint Finance Commission appears in official discussion of Union issues." },
      { question: "Why does a RAG chatbot need retrieval before answering?", statement: "Retrieval finds relevant document chunks before an answer is generated.", application: "If a user asks a difficult constitutional question, what should the system do first?", correct: "Search the documents for evidence", wrongs: ["Invent without a source", "Change color", "Delete the question"], explain: "RAG depends on retrieval so answers are grounded in sources." },
      { question: "Which practice improves accuracy in digital history education?", statement: "Answers with sources, exact dates, and clear limits reduce errors.", application: "If improving MuunganoHub, which academic priority matters most?", correct: "Answers with citations and dates", wrongs: ["Long answers without sources", "Only a larger logo", "Blocking questions"], explain: "History education needs visible evidence, dates, and sources." },
      { question: "How do the 22 Union matters help civic education?", statement: "The Union matters list helps explain the boundaries of Union responsibilities.", application: "If a student confuses government responsibilities, which list helps?", correct: "The 22 Union matters", wrongs: ["Street names", "Lesson timetable", "Sports results"], explain: "The 22 matters show areas handled as Union questions." },
      { question: "Why is shared history before 1964 important?", statement: "Trade, language, neighbourhood, and liberation history helped justify the Union.", application: "In an essay on reasons for the Union, which deeper point is best?", correct: "Social and historical foundations before 1964", wrongs: ["Only events after 2020", "School games", "Tourism only"], explain: "The Union had long-term foundations; it did not appear from nowhere." },
      { question: "Why should Union issues not be taught as a list only?", statement: "Union issues need history, institutions, solutions, and current follow-up.", application: "What should an expert lesson add beyond memorisation?", correct: "Analysis of causes and solutions", wrongs: ["Names without meaning", "One-word answers", "Avoiding sources"], explain: "Higher-level understanding requires analysing causes and how issues are handled." },
      { question: "Why were the 60 years of the Union useful for public education?", statement: "The 60th anniversary gave space to reflect on history, achievements, and debates about the Union.", application: "For a current Union lesson, which 2024 event is relevant?", correct: "The 60th anniversary of the Union", wrongs: ["Tanganyika independence in 1961", "Zanzibar Constitution of 1984", "Only the 1992 reforms"], explain: "The year 2024 marked 60 years of the Union." },
      { question: "Why are financial issues sensitive in Union discussions?", statement: "Financial issues require transparency, institutions, and fairness in implementing responsibilities.", application: "In an expert discussion on Union finance, what should be prioritized?", correct: "Institutional transparency and evidence", wrongs: ["Claims without data", "Blame without sources", "Deleting history"], explain: "Financial Union issues need evidence and institutional handling to avoid misinformation." },
      { question: "Why do Union challenges require continuous civic education?", statement: "Continuous education helps new generations understand issues, sources, and solution pathways.", application: "If a digital project wants to support Union debate, what should it do?", correct: "Provide sourced education and examples", wrongs: ["Give answers without references", "Avoid hard questions", "Use only one topic"], explain: "Union challenges continue to be discussed; civic education helps citizens follow them accurately." },
      { question: "What shows expert-level analysis of a Union challenge?", statement: "A good analysis identifies the issue origin, responsible institutions, actions taken, and current status.", application: "An expert answer about a Union challenge should include what?", correct: "Origin, institutions, actions, and current status", wrongs: ["Feelings only", "One leader's name", "A date without explanation"], explain: "Expert analysis goes beyond naming the challenge by explaining context and solution pathways." },
    ],
  };

  window.muunganoQuizQuestions = {
    sw: {
      beginner: buildLevel(sw.beginner, "sw"),
      intermediate: buildLevel(sw.intermediate, "sw"),
      expert: buildLevel(sw.expert, "sw"),
    },
    en: {
      beginner: buildLevel(en.beginner, "en"),
      intermediate: buildLevel(en.intermediate, "en"),
      expert: buildLevel(en.expert, "en"),
    },
  };
}());
